openapi: 3.0.3
info:
  title: Sinapsis Campaign Management API
  description: API para la gestión de campañas de mensajería SMS
  version: 1.0.0
  contact:
    name: Sinapsis Team
    email: dev@sinapsis.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3000/api
    description: Servidor de desarrollo local
  - url: https://api.sinapsis.com/api
    description: Servidor de producción

paths:
  /health:
    get:
      summary: Health Check
      description: Verifica el estado de la API y sus servicios
      tags:
        - Health
      responses:
        '200':
          description: Servicio funcionando correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /users:
    get:
      summary: Listar usuarios
      description: Obtiene la lista de todos los usuarios activos
      tags:
        - Users
      responses:
        '200':
          description: Lista de usuarios obtenida exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponse'

  /campaigns:
    get:
      summary: Listar campañas
      description: Obtiene la lista de campañas con filtros opcionales
      tags:
        - Campaigns
      parameters:
        - name: start_date
          in: query
          description: Fecha de inicio para filtrar (YYYY-MM-DD)
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          description: Fecha de fin para filtrar (YYYY-MM-DD)
          schema:
            type: string
            format: date
        - name: user_id
          in: query
          description: ID del usuario para filtrar
          schema:
            type: integer
        - name: status
          in: query
          description: Estado de la campaña (0=Pendiente, 1=Procesando, 2=Completada, 3=Error)
          schema:
            type: integer
            enum: [0, 1, 2, 3]
        - name: page
          in: query
          description: Número de página
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: Elementos por página
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: Lista de campañas obtenida exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignsResponse'

    post:
      summary: Crear campaña
      description: Crea una nueva campaña de mensajería
      tags:
        - Campaigns
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCampaignRequest'
      responses:
        '201':
          description: Campaña creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignResponse'
        '400':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /campaigns/{id}:
    get:
      summary: Obtener campaña por ID
      description: Obtiene los detalles de una campaña específica
      tags:
        - Campaigns
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la campaña
          schema:
            type: integer
      responses:
        '200':
          description: Detalles de la campaña obtenidos exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignDetailResponse'
        '404':
          description: Campaña no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /campaigns/{id}/process:
    post:
      summary: Procesar campaña
      description: Inicia el procesamiento de una campaña (simula envío de mensajes)
      tags:
        - Campaigns
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la campaña
          schema:
            type: integer
      responses:
        '200':
          description: Campaña procesada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessCampaignResponse'
        '400':
          description: Campaña ya procesada o datos inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /campaigns/{campaignId}/messages:
    get:
      summary: Listar mensajes de una campaña
      description: Obtiene todos los mensajes de una campaña específica
      tags:
        - Messages
      parameters:
        - name: campaignId
          in: path
          required: true
          description: ID de la campaña
          schema:
            type: integer
        - name: status
          in: query
          description: Estado del mensaje (0=Pendiente, 1=Enviado, 2=Fallido)
          schema:
            type: integer
            enum: [0, 1, 2]
        - name: page
          in: query
          description: Número de página
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: Elementos por página
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: Lista de mensajes obtenida exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessagesResponse'

  /messages/{id}:
    get:
      summary: Obtener mensaje por ID
      description: Obtiene los detalles de un mensaje específico
      tags:
        - Messages
      parameters:
        - name: id
          in: path
          required: true
          description: ID del mensaje
          schema:
            type: integer
      responses:
        '200':
          description: Detalles del mensaje obtenidos exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageDetailResponse'
        '404':
          description: Mensaje no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    HealthResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            status:
              type: string
            timestamp:
              type: string
              format: date-time
            version:
              type: string
            services:
              type: object
              properties:
                database:
                  type: string
                api:
                  type: string
            uptime:
              type: number

    UsersResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: array
          items:
            $ref: '#/components/schemas/User'

    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        status:
          type: boolean
        customer_id:
          type: integer
        customer_name:
          type: string
        total_campaigns:
          type: integer
        created_at:
          type: string
          format: date-time

    CampaignsResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            campaigns:
              type: array
              items:
                $ref: '#/components/schemas/Campaign'
            pagination:
              $ref: '#/components/schemas/Pagination'

    Campaign:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        name:
          type: string
        process_date:
          type: string
          format: date
        process_hour:
          type: string
          format: time
        process_status:
          type: integer
          enum: [0, 1, 2, 3]
        phone_list:
          type: array
          items:
            type: string
        message_text:
          type: string
        username:
          type: string
        customer_name:
          type: string
        total_messages:
          type: integer
        created_at:
          type: string
          format: date-time

    CampaignResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          $ref: '#/components/schemas/Campaign'

    CampaignDetailResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          allOf:
            - $ref: '#/components/schemas/Campaign'
            - type: object
              properties:
                sent_messages:
                  type: integer
                pending_messages:
                  type: integer
                failed_messages:
                  type: integer

    CreateCampaignRequest:
      type: object
      required:
        - user_id
        - name
        - process_date
        - process_hour
        - phone_list
        - message_text
      properties:
        user_id:
          type: integer
          minimum: 1
        name:
          type: string
          minLength: 3
          maxLength: 255
        process_date:
          type: string
          format: date
        process_hour:
          type: string
          pattern: '^([0-1]?[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'
        phone_list:
          type: array
          items:
            type: string
            pattern: '^\+?[1-9]\d{1,14}$'
          minItems: 1
        message_text:
          type: string
          minLength: 1
          maxLength: 1000

    ProcessCampaignResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            campaign_id:
              type: integer
            status:
              type: string
            total_messages:
              type: integer
            sent_messages:
              type: integer
            failed_messages:
              type: integer
            messages:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                  phone:
                    type: string
                  shipping_status:
                    type: integer
                  status_text:
                    type: string

    MessagesResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            campaign:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
            messages:
              type: array
              items:
                $ref: '#/components/schemas/Message'
            statistics:
              type: object
              properties:
                total_messages:
                  type: integer
                pending_messages:
                  type: integer
                sent_messages:
                  type: integer
                failed_messages:
                  type: integer
            pagination:
              $ref: '#/components/schemas/Pagination'

    Message:
      type: object
      properties:
        id:
          type: integer
        campaign_id:
          type: integer
        phone:
          type: string
        text:
          type: string
        shipping_status:
          type: integer
          enum: [0, 1, 2]
        status_text:
          type: string
        process_date:
          type: string
          format: date
        process_hour:
          type: string
          format: time
        created_at:
          type: string
          format: date-time

    MessageDetailResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          allOf:
            - $ref: '#/components/schemas/Message'
            - type: object
              properties:
                campaign_name:
                  type: string
                username:
                  type: string
                customer_name:
                  type: string

    Pagination:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        pages:
          type: integer

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
        errors:
          type: array
          items:
            type: object
        timestamp:
          type: string
          format: date-time

tags:
  - name: Health
    description: Endpoints de estado del servicio
  - name: Users
    description: Gestión de usuarios
  - name: Campaigns
    description: Gestión de campañas de mensajería
  - name: Messages
    description: Gestión de mensajes 