version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sinapsis_mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sinapsis_db
      MYSQL_USER: sinapsis_user
      MYSQL_PASSWORD: sinapsis_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sinapsis_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sinapsis_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - mysql
    networks:
      - sinapsis_network

volumes:
  mysql_data:

networks:
  sinapsis_network:
    driver: bridge 